import type { WeatherData } from './types';

export const indianCitiesWeather: WeatherData[] = [
  {
    city: 'Delhi',
    country: 'India',
    temperature: 32,
    condition: 'Sunny',
    humidity: 45,
    windSpeed: 10,
    aqi: 185,
    forecast: [
      { day: 'Tomorrow', condition: 'Sunny', maxTemp: 34, minTemp: 25, aqi: 190 },
      { day: 'Day 2', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 26, aqi: 175 },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 31, minTemp: 24, aqi: 160 },
    ],
  },
  {
    city: 'Mumbai',
    country: 'India',
    temperature: 29,
    condition: 'Rainy',
    humidity: 88,
    windSpeed: 25,
    aqi: 95,
    rainAlert: "Heavy rain expected in next 3 hours.",
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 30, minTemp: 26, aqi: 100, rainAlert: "Thunderstorms expected in the afternoon." },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 29, minTemp: 25, aqi: 90, rainAlert: "Continuous drizzle throughout the day." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 30, minTemp: 26, aqi: 85 },
    ],
  },
  {
    city: 'Bangalore',
    country: 'India',
    temperature: 24,
    condition: 'Cloudy',
    humidity: 75,
    windSpeed: 15,
    aqi: 65,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 26, minTemp: 20, aqi: 70 },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 24, minTemp: 20, aqi: 60, rainAlert: "Light showers in the evening." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 25, minTemp: 21, aqi: 68 },
    ],
  },
  {
    city: 'Chennai',
    country: 'India',
    temperature: 31,
    condition: 'Partly Cloudy',
    humidity: 70,
    windSpeed: 18,
    aqi: 110,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 27, aqi: 115 },
      { day: 'Day 2', condition: 'Sunny', maxTemp: 34, minTemp: 28, aqi: 120 },
      { day: 'Day 3', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 27, aqi: 105 },
    ],
  },
  {
    city: 'Kolkata',
    country: 'India',
    temperature: 30,
    condition: 'Cloudy',
    humidity: 82,
    windSpeed: 12,
    aqi: 130,
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 31, minTemp: 26, aqi: 135, rainAlert: "Heavy rain and strong winds warning." },
      { day: 'Day 2', condition: 'Cloudy', maxTemp: 30, minTemp: 25, aqi: 125 },
      { day: 'Day 3', condition: 'Rainy', maxTemp: 29, minTemp: 25, aqi: 120, rainAlert: "Chance of afternoon thunderstorms." },
    ],
  },
  {
    city: 'Visakhapatnam',
    country: 'India',
    temperature: 30,
    condition: 'Partly Cloudy',
    humidity: 78,
    windSpeed: 20,
    aqi: 105,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 32, minTemp: 27, aqi: 110 },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 30, minTemp: 26, aqi: 95, rainAlert: "Scattered showers expected." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 31, minTemp: 27, aqi: 100 },
    ],
  },
  {
    city: 'Thiruvananthapuram',
    country: 'India',
    temperature: 28,
    condition: 'Rainy',
    humidity: 85,
    windSpeed: 18,
    aqi: 75,
    rainAlert: "Ongoing light rain.",
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 29, minTemp: 24, aqi: 80, rainAlert: "Heavy rainfall warning for tomorrow." },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 28, minTemp: 24, aqi: 70, rainAlert: "Expect intermittent rain." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 29, minTemp: 25, aqi: 72 },
    ],
  },
];

export const defaultCity = 'Delhi';
