import type { WeatherData } from './types';

export const indianCitiesWeather: WeatherData[] = [
  {
    city: 'Delhi',
    country: 'India',
    temperature: 32,
    feelsLike: 36,
    condition: 'Sunny',
    humidity: 45,
    windSpeed: 10,
    aqi: 185,
    forecast: [
      { day: 'Tomorrow', condition: 'Sunny', maxTemp: 34, minTemp: 25, feelsLike: 38, aqi: 190, precipitation: 5 },
      { day: 'Day 2', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 26, feelsLike: 37, aqi: 175, precipitation: 10 },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 31, minTemp: 24, feelsLike: 34, aqi: 160, precipitation: 20 },
    ],
  },
  {
    city: 'Mumbai',
    country: 'India',
    temperature: 29,
    feelsLike: 34,
    condition: 'Rainy',
    humidity: 88,
    windSpeed: 25,
    aqi: 95,
    rainAlert: "Heavy rain expected in next 3 hours.",
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 30, minTemp: 26, feelsLike: 35, aqi: 100, precipitation: 90, rainAlert: "Thunderstorms expected in the afternoon." },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 29, minTemp: 25, feelsLike: 34, aqi: 90, precipitation: 85, rainAlert: "Continuous drizzle throughout the day." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 30, minTemp: 26, feelsLike: 35, aqi: 85, precipitation: 40 },
    ],
  },
  {
    city: 'Bangalore',
    country: 'India',
    temperature: 24,
    feelsLike: 26,
    condition: 'Cloudy',
    humidity: 75,
    windSpeed: 15,
    aqi: 65,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 26, minTemp: 20, feelsLike: 28, aqi: 70, precipitation: 20 },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 24, minTemp: 20, feelsLike: 25, aqi: 60, precipitation: 60, rainAlert: "Light showers in the evening." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 25, minTemp: 21, feelsLike: 27, aqi: 68, precipitation: 30 },
    ],
  },
  {
    city: 'Chennai',
    country: 'India',
    temperature: 31,
    feelsLike: 37,
    condition: 'Partly Cloudy',
    humidity: 70,
    windSpeed: 18,
    aqi: 110,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 27, feelsLike: 39, aqi: 115, precipitation: 15 },
      { day: 'Day 2', condition: 'Sunny', maxTemp: 34, minTemp: 28, feelsLike: 40, aqi: 120, precipitation: 5 },
      { day: 'Day 3', condition: 'Partly Cloudy', maxTemp: 33, minTemp: 27, feelsLike: 39, aqi: 105, precipitation: 20 },
    ],
  },
  {
    city: 'Kolkata',
    country: 'India',
    temperature: 30,
    feelsLike: 36,
    condition: 'Cloudy',
    humidity: 82,
    windSpeed: 12,
    aqi: 130,
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 31, minTemp: 26, feelsLike: 37, aqi: 135, precipitation: 80, rainAlert: "Heavy rain and strong winds warning." },
      { day: 'Day 2', condition: 'Cloudy', maxTemp: 30, minTemp: 25, feelsLike: 36, aqi: 125, precipitation: 45 },
      { day: 'Day 3', condition: 'Rainy', maxTemp: 29, minTemp: 25, feelsLike: 35, aqi: 120, precipitation: 70, rainAlert: "Chance of afternoon thunderstorms." },
    ],
  },
  {
    city: 'Visakhapatnam',
    country: 'India',
    temperature: 30,
    feelsLike: 35,
    condition: 'Partly Cloudy',
    humidity: 78,
    windSpeed: 20,
    aqi: 105,
    forecast: [
      { day: 'Tomorrow', condition: 'Partly Cloudy', maxTemp: 32, minTemp: 27, feelsLike: 37, aqi: 110, precipitation: 25 },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 30, minTemp: 26, feelsLike: 35, aqi: 95, precipitation: 55, rainAlert: "Scattered showers expected." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 31, minTemp: 27, feelsLike: 36, aqi: 100, precipitation: 30 },
    ],
  },
  {
    city: 'Thiruvananthapuram',
    country: 'India',
    temperature: 28,
    feelsLike: 32,
    condition: 'Rainy',
    humidity: 85,
    windSpeed: 18,
    aqi: 75,
    rainAlert: "Ongoing light rain.",
    forecast: [
      { day: 'Tomorrow', condition: 'Rainy', maxTemp: 29, minTemp: 24, feelsLike: 33, aqi: 80, precipitation: 95, rainAlert: "Heavy rainfall warning for tomorrow." },
      { day: 'Day 2', condition: 'Rainy', maxTemp: 28, minTemp: 24, feelsLike: 32, aqi: 70, precipitation: 85, rainAlert: "Expect intermittent rain." },
      { day: 'Day 3', condition: 'Cloudy', maxTemp: 29, minTemp: 25, feelsLike: 33, aqi: 72, precipitation: 40 },
    ],
  },
];

export const defaultCity = 'Delhi';
